import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import "./globals.css";
import { extractRouterConfig } from "uploadthing/server";
import React from "react";

import { ourFileRouter } from "@/app/api/uploadthing/core";

//providers
import { SearchProvider } from "./Contexts/searchContext";
import { AuthProvider } from "./Contexts/authContext";
import { ReactQueryProvider } from "./Contexts/reactQueryContext";
import { PageProvider } from "./Contexts/pageContext";
import { CreateCarProvider } from "./Contexts/createCarContext";
import { CarDetailsProvider } from "./Contexts/carDetailsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ReactQueryProvider>
            <AuthProvider>
                <PageProvider>
                    <SearchProvider>
                        <CreateCarProvider>
                            <CarDetailsProvider>
                                <html lang="en">
                                    <body className={inter.className}>
                                        <NextSSRPlugin
                                            routerConfig={extractRouterConfig(
                                                ourFileRouter
                                            )}
                                        />
                                        {children}
                                    </body>
                                </html>
                            </CarDetailsProvider>
                        </CreateCarProvider>
                    </SearchProvider>
                </PageProvider>
            </AuthProvider>
        </ReactQueryProvider>
    );
}
