import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import "./globals.css";
import { extractRouterConfig } from "uploadthing/server";
import React from "react";

import { ourFileRouter } from "@/app/api/uploadthing/core";

//providers
import { SearchProvider } from "./Contexts/searchContext";
import { AuthProvider } from "./Contexts/authContext";
import { ReactQueryProvider } from "./Contexts/reactQueryContext";
import { PageProvider } from "./Contexts/pageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ReactQueryProvider>
            <AuthProvider>
                <PageProvider>
                    <SearchProvider>
                        <html lang="en">
                            <body className={inter.className}>
                                <NextSSRPlugin
                                    /**
                                     * The `extractRouterConfig` will extract **only** the route configs
                                     * from the router to prevent additional information from being
                                     * leaked to the client. The data passed to the client is the same
                                     * as if you were to fetch `/api/uploadthing` directly.
                                     */
                                    routerConfig={extractRouterConfig(
                                        ourFileRouter
                                    )}
                                />
                                {children}
                            </body>
                        </html>
                    </SearchProvider>
                </PageProvider>
            </AuthProvider>
        </ReactQueryProvider>
    );
}
